### ISSUE TITLE
泛解析

### ISSUE THREAD

**Issue by 5z1punch** [FeeiCN/ESD#1]
域名爆破遇到泛解析挺常见的，还是应该解决下，我觉得chu的这个文章中，ip+ttl的方法效果应该还是不错的
http://sh3ll.me/archives/201704041222.txt

**Comment by FeeiCN** [comment]
对于泛解析的架构来说，他大部分子域都解析到同样的几台Proxy上，IP+TTL黑名单是解决不了这类情况的。

唯一的解决方式是遍历所有字典的二级域名，并获取返回内容，使用返回内容做相似度匹配。这个方案也尝试过，时间成本太高。
