### ISSUE TITLE
不太明白刚开始为什么要对不存在的域名进行requests请求？

### ISSUE THREAD

**Issue by zhaoyuyuan** [FeeiCN/ESD#11]
1.做了泛解析的域名，不存在的子域名能解析到一个IP，但这个子域名或对应的IP 不一定开放http/https服务啊！，，后续进行相似比较，只要是域名存在但没有开发http 服务的，都会被漏掉吧。

2. 不知道要不要控制dns解析并发量？感觉还是要控制下。

**Comment by zhaoyuyuan** [comment]
额，控制dns并发量了，看晕乎了。但是第一点还是不太理解呀

**Comment by FeeiCN** [comment]
@zhaoyuyuan 
你可以看看我这篇，如果还还有不明白的可以问我
http://feei.cn/esd
