### ISSUE TITLE
提供一个误报

### ISSUE THREAD

**Issue by leveryd** [FeeiCN/ESD#20]
扫描fangdd.com，子域名中很多的误报，如下图。
python esd.py fangdd.com
![image](https://user-images.githubusercontent.com/1846319/40177552-7d1dd454-5a11-11e8-8621-60c352eb4ecc.png)

我初步看了一下原因，是因为
xjiaijf-azz.fangdd.com、fajijixa-bb.fangdd.com  等是相同的页面
aaaa.fangdd.com、bbbbbb.fangdd.com  等是另外一种相同的页面

**Comment by FeeiCN** [comment]
@leveryd 感谢提供

**Comment by FeeiCN** [comment]
@leveryd 更新最新版本，使用过滤功能
```bash
python ESD.py fangdd.com 服务器出了点问题
```
