### ISSUE TITLE
关于泛解析的问题

### ISSUE THREAD

**Issue by Lyttoni** [FeeiCN/ESD#4]
泛解析域名并不是不能扫描，可以试着通过随机1000个子域解析出的IP，来添加一个泛解析的IP黑名单。在接下来的扫描中，只需要忽略解析到了黑名单IP的域名就好... 😆

**Comment by FeeiCN** [comment]
@Lyttoni 
太理想了，你可以看看蘑菇街的架构，所有域名解析到同一个Proxy集群（同一批IP），按照你的方式把这同一批IP放入黑名单将会把后续所有域名都忽略了。

泛解析的问题目前来看只能通过先获取一个绝对不存在的域名Response，再匹配所有子域名的Response，计算相似度来枚举子域名。

**Comment by Lyttoni** [comment]
好吧... 学习了 谢谢大佬
