### ISSUE TITLE
能把shodan,censys，等接口加进去吗

### ISSUE THREAD

**Issue by wolyty** [FeeiCN/ESD#67]
能把shodan,censys，等接口加进去吗

**Comment by FeeiCN** [comment]
参照https://github.com/caffix/amass，增加APIs: BinaryEdge, BufferOver, CIRCL, HackerTarget, PassiveTotal, Robtex, SecurityTrails, Shodan, Twitter, Umbrella, URLScan

**Comment by FeeiCN** [comment]
fixed #74
