### ISSUE TITLE
label empty or too long

### ISSUE THREAD

**Issue by 1522402210** [FeeiCN/ESD#8]
Sub domain dict count: 735300
2018-04-11 12:17:05,165 [ESD] [INFO] Generate coroutines...
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

**Comment by FeeiCN** [comment]
@1522402210 能复现吗？

**Comment by 1522402210** [comment]
字典加入：
autoconfig.main
autoconfig.media
autoconfig.member
autoconfig.members
autoconfig.mobile
autoconfig.movies
autoconfig.movil
autoconfig.music
autoconfig.my
autoconfig.new
autoconfig.news
autoconfig.newsletter
autoconfig.old
autoconfig.online
autoconfig.portal
autoconfig.projects
autoconfig.radio
autoconfig.reseller
autoconfig.sandbox
autoconfig.search
autoconfig.secure
autoconfig.seo
autoconfig.server
autoconfig.shop
autoconfig.sms
autoconfig.soporte
autoconfig.sports
autoconfig.stage
autoconfig.staging
autoconfig.static
autoconfig.store
autoconfig.support
autoconfig.test
autoconfig.testing
autoconfig.tickets
autoconfig.travel
autoconfig.tv
autoconfig.us
autoconfig.v2
autoconfig.video
autoconfig.videos
autoconfig.web
autoconfig.webdesign
autoconfig.webmail
autoconfig.wholesale
autoconfig.wiki
autoconfig.wordpress
autoconfig.wp
autoconfig.www2
autoconfig.x
autodesk
autodiscover-redirect
autodiscover.admin
autodiscover.ads
autodiscover.api
autodiscover.app
autodiscover.archive
autodiscover.beta
autodiscover.billing
autodiscover.blog
autodiscover.blogs
autodiscover.business
autodiscover.cdn
autodiscover.chat
autodiscover.classifieds
autodiscover.client
gitalist-01
gitalist-02
gitalist-03
gitalist-1
gitalist-2
gitalist-3
gitalist01
gitalist02
gitalist03
gitalist1
gitalist2
gitalist3
github-01
github-02
github-03
github-1
github-2
github-3
github01
github02
github03
github1
github2
github3
gitlab-01
gitlab-02
gitlab-03
gitlab-1
gitlab-2
gitlab-3
gitlab01
gitlab02
gitlab03

试试

**Comment by FeeiCN** [comment]
@1522402210 
字典不符合ESD的要求导致的，具体表现为你的字典前后可能存在（.）。
已做兼容处理。
