### ISSUE TITLE
环境要求？

### ISSUE THREAD

**Issue by chaozai1028l** [FeeiCN/ESD#84]
目前，uvloop不支持Windows系统和Python 3.5 及其以上版本，这在它源码的setup.py文件中可以看到：

if sys.platform in ('win32', 'cygwin', 'cli'):
    raise RuntimeError('uvloop does not support Windows at the moment')

vi = sys.version_info
if vi < (3, 5):
    raise RuntimeError('uvloop requires Python 3.5 or greater')
所以，使用Windows的小猿们要运行异步爬虫，就要把uvloop那两行注释掉哦。

安装esd过程中出现 uvloop报错，  有么有更好的解决方法

**Comment by FeeiCN** [comment]
目前不支持windows
