### ISSUE TITLE
shodan.exception.APIError: Please upgrade your API解决办法

### ISSUE THREAD

**Issue by skytina** [FeeiCN/ESD#92]
>问题描述: ESD支持配置shodan_key来进行使用domain语法搜索子域名，但是普通的shodan账号会出现shodan.exception.APIError: Please upgrade your API plan to use filters or paging.错误。一旦出错后不管如何重新安装ESD库也还是会出错

问题根本:
ESD在使用shodan库会进行初始化，会在用户家目录的api_key或者ESD库目录下取key.ini得shodan节段的内容

解决办法:
步骤1. 切换到当前用户的家目录下
```bash
cd ~/.shodan
rm -f api_key
```

步骤2. 切换到ESD库目录底下
```bash
#这里的ESD目录请切换成自己的
find / -name "key.ini" 2>/dev/null
cd /usr/local/lib/python3.7/site-packages/ESD/
rm key.ini
```

**Comment by FeeiCN** [comment]
最新版已修复
